spring.application.name=lms

spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://localhost:3306/spring-boot-demo
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/lmsdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=false
#Token
jwt.secret=${JWT_SECRET:LmsSecretKey1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop}
jwt.expiration=3600000
#jwt.expiration=10000
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ========== MAIL CONFIG ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:akashmmn03@gmail.com}
spring.mail.password=${MAIL_PASSWORD:sfxeiajgwqfdrclm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.number=${TWILIO_WHATSAPP_NUMBER:whatsapp:+14155238886}
twilio.phone.number=${TWILIO_PHONE_NUMBER:+18202042432}